# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: mandelbrot
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-12-clang-14-native:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        compiler: [ g++-12, clang++-14 ]
        standard: [ c++14, c++17, c++20, c++2b ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: clone-submods-bootstrap-headers-boost-develop
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
          cd ../boost-root
          git submodule update --init tools
          git submodule update --init libs/array
          git submodule update --init libs/assert
          git submodule update --init libs/concept_check
          git submodule update --init libs/config
          git submodule update --init libs/container
          git submodule update --init libs/container_hash
          git submodule update --init libs/core
          git submodule update --init libs/detail
          git submodule update --init libs/filesystem
          git submodule update --init libs/functional
          git submodule update --init libs/gil
          git submodule update --init libs/integer
          git submodule update --init libs/io
          git submodule update --init libs/iterator
          git submodule update --init libs/lexical_cast
          git submodule update --init libs/move
          git submodule update --init libs/mp11
          git submodule update --init libs/mpl
          git submodule update --init libs/multiprecision
          git submodule update --init libs/numeric/conversion
          git submodule update --init libs/preprocessor
          git submodule update --init libs/range
          git submodule update --init libs/smart_ptr
          git submodule update --init libs/static_assert
          git submodule update --init libs/system
          git submodule update --init libs/throw_exception
          git submodule update --init libs/type_traits
          git submodule update --init libs/utility
          git submodule update --init libs/variant2
          ./bootstrap.sh
          ./b2 headers
      - name: update compilers
        run: sudo apt install g++-12 clang-14
      - name: install gmp
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --no-install-recommends --quiet --yes libgmp-dev
      - name: gcc-12-clang-14-native
        run: |
          echo "query GCC version"
          g++ -v
          echo "build libjpeg-6b.a"
          cd jpeg
          make all
          cd ..
          echo '${{ matrix.compiler }} -c -finline-functions -march=native -mtune=native -O3 -Wall -Wextra -std=${{ matrix.standard }} -DMANDELBROT_USE_GMP_FLOAT -I. -Ijpeg/jpeg-6b-2022 -I../boost-root -pthread test/test_mandelbrot.cpp -o test_mandelbrot.o'
          ${{ matrix.compiler }} -c -finline-functions -march=native -mtune=native -O3 -Wall -Wextra -std=${{ matrix.standard }} -DMANDELBROT_USE_GMP_FLOAT -I. -Ijpeg/jpeg-6b-2022 -I../boost-root -pthread test/test_mandelbrot.cpp -o test_mandelbrot.o
          echo '${{ matrix.compiler }} test_mandelbrot.o -lpthread -lgmp -ljpeg-6b -Ljpeg/jpeg-6b-2022/obj -o test_mandelbrot.exe'
          ${{ matrix.compiler }} test_mandelbrot.o -lpthread -lgmp -ljpeg-6b -Ljpeg/jpeg-6b-2022/obj -o test_mandelbrot.exe
          ls -la ./test_mandelbrot.exe
          mkdir -p images/tmp
          ./test_mandelbrot.exe
          ls -la ./images/tmp/mandelbrot_MANDELBROT_05_SEAHORSES.jpg
